### ISSUE TITLE
Text formatting on node screen appears broken on 2.3.0

### ISSUE THREAD

**Issue by eldoctorcool** [meshtastic/Meshtastic-Android#907]
Attached image is how 2.3.0 now looks... vs 2.2.24
2.3--> Broken...
![IMG_20240312_020031](https://github.com/meshtastic/Meshtastic-Android/assets/163106244/a21948c7-f402-4415-b257-f719aa7351cc)

2.2.24 ---> works.
![IMG_20240312_023450](https://github.com/meshtastic/Meshtastic-Android/assets/163106244/7c1b4a24-71ab-4903-b5e5-24626e379cc2)

**Comment by tropho23** [comment]
Try uninstalling the app, then reinstalling it fresh. I am running the same version of this app and do not experience this problem.

If the problem persists please provide your phone make and model, your Android operating system version, and anything else you think might be relevant.

**Comment by prokrypt** [comment]
This is due to a combination of small screen and large font size. Setting a smaller system font in Android settings should make the coordinates of other nodes stay on one line. The info on the connected node, however, looks like it needs some layout/wrapping adjustment.

**Comment by prokrypt** [comment]
Some examples: largest display, larger (largest) font size
![Screenshot_20240312-092738-708](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/87159707-de7f-4258-b998-e6f05db0c1c6)

largest display, large font size:
![Screenshot_20240312-092823-539](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/04039375-8fad-4d28-b690-220d01d4508d)

**Comment by eldoctorcool** [comment]
Reinstalling the app, cleared cache, etc. all that didn't do anything. This is an Android 7.1.2 generic unbranded device that has worked fine with the Meshstastic Android app for over a year now. Device physical screen is 3 1/4 inches. The font size and screen size are just a notch above default size, (not largest) but this problem also happens with default font and screen size. 

Given that 2.2.24 worked just fine but 2.3 doesn't, I would to please ask if someone could please fix this? Thank you very much.

**Comment by Hardbuckle** [comment]
Same issue. Using portrait caused text down the screen. All OK until 2.3.0. 
OnePlus Open in front screen portrait (normal use). Tried all of the above. All  OK previously.

**Comment by Hardbuckle** [comment]
![IMG_20240313_073700](https://github.com/meshtastic/Meshtastic-Android/assets/131908745/c6bb4bd0-d4d9-4c96-8d29-7338c7ea8875)

**Comment by eldoctorcool** [comment]
Has this been addressed in 2.3.1? Thanks.

**Comment by eldoctorcool** [comment]
2.3.1 and 2.3.2 tested. The formatting still broken.

**Comment by Bryang0syr** [comment]
Last night 2.3.2 was pushed out onto my Samsung A13 so I woke up this morning to find the above formatting issues. I presume 2.3.0 and 2.3.1 had not been pushed onto my phone when they were released as this is first time I've been aware of the issue. Format is displayed ok in Landscape mode so only an issue in portrait mode

**Comment by Hardbuckle** [comment]
Agreed. Formatted still broken in 2.3.2 portrait. Very annoying when half the screen is lost to one node.

**Comment by francisuk1989** [comment]
I have no issues on my google pixel 8 pro
![image](https://github.com/meshtastic/Meshtastic-Android/assets/11011688/4b9d23fa-ff84-4665-a505-f0741f61d4b5)

**Comment by asjmcguire** [comment]
There's a chance it was fixed for us beta testers in https://github.com/meshtastic/Meshtastic-Android/commit/e3f495e35261e46ae818c7d32b96ee9a1bae472a

**Comment by eldoctorcool** [comment]
> There's a chance it was fixed for us beta testers in [e3f495e](https://github.com/meshtastic/Meshtastic-Android/commit/e3f495e35261e46ae818c7d32b96ee9a1bae472a)

It is not. I've tried and 2.3.2 has that fix, its not fixed.

**Comment by francisuk1989** [comment]
A new beta has been pushed out sometime on the 2nd of April via Google Play Store, How's everyone find it now if on the Beta?

If you not on the android beta, Go to Google Play Store > search for meshtastic- > scroll down to Join Beta Program and then give it 10mins and there should be a update, if you can also leave the beta at anytime.

**Comment by Hardbuckle** [comment]
No improvement. The same issue on 2.3.3
![Screenshot_2024-04-03-16-33-26-47_24570ffaa6dee6a40011f001254fdfdb](https://github.com/meshtastic/Meshtastic-Android/assets/131908745/9de7404e-6054-4f3a-bb1a-ae661d791f6e)

**Comment by eldoctorcool** [comment]
Same here. No improvement. 

I get my beta/alpha builds directly from github. So, whatever its latest on the app, I get to test.

**Comment by andrekir** [comment]
this was fixed in recent releases. closing.
